<a href="https://colab.research.google.com/github/ArtemkaDS/homework/blob/main/%22Part_1_HW_Write_our_own_library_ipynb%22(HW_3_extended).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Домашнее задание. Часть 1.

- напишем свою собственную библиотеку

Вего за эту часть ДЗ можно набрать максимум **11.5 баллов**. Разбиение баллов по каждой из задач представлено непосредственно перед текстом каждой задачи.

**Дедлайн - пятница, 11.12.2020 в 23:59.**

Дедлайн жесткий, сдача после дедлайна - 0 баллов за ДЗ.

Ссылка на ноутбук в колабе: https://colab.research.google.com/drive/1LgWtESFmiNW1WlVFCHKyNl_BxAWxoL3Z?usp=sharing

Допустим мы хотим написать фнкцию, которая складывает 2 числа и сохранить ее в отдельный .py файл. Пример:

In [ ]:
%%writefile lib.py
def summ(a1, b1):
    return a1+b1

Writing lib.py


In [ ]:
from lib import summ

In [ ]:
summ(2,6)

8

Попробуем запустить через "терминал"

In [ ]:
!python3 lib.py

Ничего не происходит. А теперь добавим `if __name__ == "__main__"` в наш код и пересохраним файл lib.py

In [ ]:
%%writefile lib.py
import sys

a1 = float( sys.argv[1] ) # Считываем аргументы прямо из терминала
b1 = float( sys.argv[2] ) # Считываем аргументы прямо из терминала

def summ(a1, b1):
    return a1+b1

if __name__ == "__main__":
    print(summ(a1, b1))


Overwriting lib.py


In [ ]:
!python3 lib.py 2 4

6.0


# **Задание 1**

Реализуйте следующие функции и сохраните их в библиотеку **my_math_lib.py** (пока без использования конструкции `if __name__ == "__main__"`)

**1 point** 
1. **def deg_to_rad()**. Напишите программу на Python для преобразования градусов в радианы.  *(Note: Радиан - это стандартная единица измерения угла, используемая во многих областях математики. Измерение угла в радианах численно равно длине соответствующей дуги единичного круга; один радиан чуть меньше 57,3 градуса)* **1 point**

**1 point** 
2. **def rad_to_def()**. Напишите программу Python для преобразования радианов в градусы.

**1.5 point** 
3. **def discriminant()**. Напишите программу на Python для вычисления значения дискриминанта (вспоминаем квадратные уравнения). Входные данные три числа: x, y, z (учтите что корни могут быть комлЕксными!)

**1.5 point** 
4. **def power_base_sum()**. Напишите программу на Python, чтобы вычислить сумму всех цифр основания в указанной степени.

Пример: power_base_sum(2, 100)

Выход: 115



**2 point** 
5. **def magic_square()**. Напишите программу на Python для вычисления [магического квадрата](https://ru.wikipedia.org/wiki/Магический_квадрат)

Note:

Магический, или волшебный квадрат — это квадратная таблица , заполненная числами таким образом, что сумма чисел в каждой строке, каждом столбце и на обеих диагоналях одинакова. Сумма чисел в каждой строке, столбце и на диагоналях, называется магической константой, M.

**1 point** 
6. **def mult_list()**. Напишите функцию Python для умножения всех чисел в массиве list(), (размер листа на входе произвольный)

**1 point** 
7. **def create_list()**. Напишите функцию Python для создания и вывода списка (при помощи print()), в котором значения представляют собой квадрат чисел от 1 до 30 (оба включительно).

In [ ]:
#TODO
%%writefile my_math_lib.py

import numpy as np

def deg_to_rad(deg):
    rad = deg / 57.2958
    return rad

def rad_to_deg(rad):
    deg = rad * 57.2958
    return deg

def discriminant(x,y,z):
    discriminant = (y ** 2) - (4 * x * z)
    return discriminant

def power_base_sum(base, power):
    return sum([int(i) for i in str(pow(base, power))])

def magic_square(n):
    magic_square = np.zeros((n, n), dtype='int64')
    count = 1
    x = 0
    y = n // 2
    while count <= n ** 2:
        magic_square[x, y] = count
        count += 1
        x1 = (x - 1) % n
        y1 = (y + 1) % n
        if magic_square[x1, y1]:
            x += 1
        else:
            x = x1
            y = y1
    return magic_square

def mult_list():
    list = [int(i) for i in input().split()]
    result = np.prod(list)
    return result

def mult_list_1():
    list = [int(i) for i in input().split()]
    res = 1
    for i in list:
        res *= i
    return res

def create_list():
    list_done = []
    list = [int(i) for i in range(1,31)]
    for i in list:
        i **= 2
        list_done.append(i)
    print(list_done)

Writing my_math_lib.py


# **Задание 2**
Импортируйте все методы из модуля my_math_lib.

 **0.25 point** 
 - при помощи функции **def discriminant()** посчитайте дискриминант следующего уравнения: 
 $x^{2}+3 x+4=0$

**0.25 point** 
 - постройте магический квадрат размера 5х5

In [ ]:
from my_math_lib import * #TODO

In [ ]:
discriminant(1,3,4)

-7

In [ ]:
magic_square(5)

array([[17, 24,  1,  8, 15],
       [23,  5,  7, 14, 16],
       [ 4,  6, 13, 20, 22],
       [10, 12, 19, 21,  3],
       [11, 18, 25,  2,  9]])

# **Задание 3**

**2 point**
* Добавьте в вашу библиотеку конструкцию `if __name__ == "__main__"`, которая должна принимать одну из вышеперечисленных функций. 
* Важно! аргументы, подаваемые в функцию, должны подаваться напряму через терминал (как в примере)! Используйте для этого библиотеку `sys`

In [10]:
#TODO
# Выбрал функцию magic_square
%%writefile my_math_lib.py

import numpy as np
import sys

def deg_to_rad(deg):
    rad = deg / 57.2958 #либо импортировать math и юзать pi
    return rad

def rad_to_deg(rad):
    deg = rad * 57.2958
    return deg

def discriminant(x,y,z):
    discriminant = (y ** 2) - (4 * x * z)
    return discriminant

def power_base_sum(base, power):
    return sum([int(i) for i in str(pow(base, power))])

n = int( sys.argv[1] )

def magic_square(n):
    magic_square = np.zeros((n, n), dtype='int64')
    count = 1
    x = 0
    y = n // 2
    while count <= n ** 2:
        magic_square[x, y] = count
        count += 1
        x1 = (x - 1) % n
        y1 = (y + 1) % n
        if magic_square[x1, y1]:
            x += 1
        else:
            x = x1
            y = y1
    return magic_square

if __name__ == "__main__":
    print(magic_square(n))

def mult_list():
    list = [int(i) for i in input().split()]
    result = np.prod(list)
    return result

def mult_list_1():
    list = [int(i) for i in input().split()]
    res = 1
    for i in list:
        res *= i
    return res

def create_list():
    list_done = []
    list = [int(i) for i in range(1,31)]
    for i in list:
        i **= 2
        list_done.append(i)
    print(list_done)

Overwriting my_math_lib.py


In [11]:
# Пример вызова функции - Вы можете вызвать любую другую
!python3 my_math_lib.py 9 # Например если в __main__ вы указали def discriminant()

[[47 58 69 80  1 12 23 34 45]
 [57 68 79  9 11 22 33 44 46]
 [67 78  8 10 21 32 43 54 56]
 [77  7 18 20 31 42 53 55 66]
 [ 6 17 19 30 41 52 63 65 76]
 [16 27 29 40 51 62 64 75  5]
 [26 28 39 50 61 72 74  4 15]
 [36 38 49 60 71 73  3 14 25]
 [37 48 59 70 81  2 13 24 35]]
